### ISSUE TITLE
Seems to be broken??

### ISSUE THREAD

**Issue by mattprother** [micro2112/Lowes2019#5]
First of all, thanks for everything you have done for this. I have contributed in the past to your paypal as you have saved me money on our home.

i haven't used this in awhile, but it seems to be broken as the green check price button is missing. hopefully it is just me. 

thanks again and have a good thanksgiving!

**Comment by austinsec** [comment]
It is working make sure they dont blacklist your ip slow the search.

**Comment by mattprother** [comment]
ok, good to know. i'm using firefox. i'll just retart my cpu/firefox. sorry for the fire drill.

close the issue please

**Comment by micro2112** [comment]
NP. I'm just happy to see that people like/use the script. It is a fun project for me to maintain.
