### ISSUE TITLE
Lowes2019 Inventory/Price Tracker

### ISSUE THREAD

**Issue by amanvirs** [micro2112/Lowes2019#6]
Hi,

This comment isn't to report an issue for your lowes script - i love it! 

I just wanted to know if you had something similar for home depot?

**Comment by micro2112** [comment]
I have never looked in to to adopting this code for HD, there would be several hurdles i need to figure out to pull that off.

**Comment by austinsec** [comment]
Hey is the script down?

**Comment by austinsec** [comment]
cant seem to get search button to pop up

**Comment by micro2112** [comment]
The script is still working for me in Chrome & FF.

**Comment by austinsec** [comment]
I got it up again by erasing all settings on chrome. I think they are
playing around with the site. Thank you for the quick response.
